#!/bin/bash

cat <<EOF
Basic usage:

    /join <channel> to join a channel
    /part [<message>] to leave a channel
    /msg <target> <message> to send a PRIVMSG
    /raw <text> to send raw text directly to the server
    
    M-Left to go to the previous channel
    M-Right to go to next channel

    The following behave as you would expect if you were using readline:
        C-a
        C-e
        C-k

    If you press Tab, the client will attempt to auto-complete
    the word you are typing as a nickname of a user who has recently
    spoken.

    C-w is the same as doing /part.

    Mouse-wheel scrolling is supported.

    C-c to quit


Please enter your information for connecting to freenode, and
a configuration file will be generated for you.

EOF

read -p "Nick: " nick
read -p "Username: " username
read -s -p "Password: " password

echo
echo "Setting up configuration file..."

cat > ~/.irc.conf <<EOF
[user]
nick = $nick
username = $username
auth = $(printf "$username\0$username\0$password" | base64)

[colors]
normal       = 230  25
input        = 230  33
warning      = 203  25
notification = 250  25
timestamp    = 250  25
nick         = 186  25
mynick       = 180  25
mention      = 169  25
action       = 226  25
activity     = 51   25
important    = 203  25

[channels]
; channels listed here will be auto-joined on startup
; ##c
; #freenode

[misc]
; Maximum amount of characters of a nick to render.
; The max on freenode is 16, but it takes up a lot of space.
; RFC 1459 had 9 as the max.
nicklength = 9

; Auto switch to private chat if somebody sends you
; a private message.
autoswitch = off
EOF

echo "Done! You can find the configuration file at ~/.irc.conf"
